---
# tasks file for amaudy.deployer
- name: Add Linux User
  user: name={{ deploy_user }} shell=/bin/bash createhome=yes comment='Created by Ansible'

- name: Creates .ssh directory
  file:
    path: '/home/{{ deploy_user }}/.ssh'
    state: directory
    owner: '{{ deploy_user }}'
    group: '{{ deploy_user }}'

- name: Added public key to server.
  authorized_key:
    user: '{{ deploy_user }}'
    key: '{{deploy_key}}'
